### ISSUE TITLE
Lab 2

### ISSUE THREAD

**Issue by jsrc1115** [LuimarcoCarrascalDiaz/Lab2SummerSchoolAI#1]
Good morning Luimarco, about the Lab:

For the first point, the examples I mentioned in the lab are related to what we were working in class, I'm attaching the python files and the requirements file so you can complete the point too.

Please complete 2nd point I believe it is not finished yet, if you have any questions you can reach out to me through this GitHub issue thread.

[point_1_files.zip](https://github.com/user-attachments/files/16335963/point_1_files.zip)

Regards,
Juan Rodriguez

**Comment by LuimarcoCarrascalDiaz** [comment]
I will work on it through the day
Luimarco

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: jsrc1115 ***@***.***>
Enviado: Monday, July 22, 2024 10:12:06 AM
Para: LuimarcoCarrascalDiaz/Lab2SummerSchoolAI ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [LuimarcoCarrascalDiaz/Lab2SummerSchoolAI] Lab 2 (Issue #1)


Good morning Luimarco, about the Lab:

For the first point, the examples I mentioned in the lab are related to what we were working in class, I'm attaching the python files and the requirements file so you can complete the point too.

Please complete 2nd point I believe it is not finished yet, if you have any questions you can reach out to me through this GitHub issue thread.

point_1_files.zip<https://github.com/user-attachments/files/16335963/point_1_files.zip>

Regards,
Juan Rodriguez

**Comment by sebastianrodriguez1115** [comment]
Good afternoon Luimarco, I see you have not updated the code, I think it has been enough time, I will grade whatever is uploaded at the end of today.

Regards,
Juan Rodriguez

**Comment by LuimarcoCarrascalDiaz** [comment]
hello, so i have been struggling with the setup in the project
________________________________
De: sebastianrodriguez1115 ***@***.***>
Enviado: martes, 23 de julio de 2024 3:51 p. m.
Para: LuimarcoCarrascalDiaz/Lab2SummerSchoolAI ***@***.***>
Cc: Luimarco Daniel Santiago Carrascal Diaz ***@***.***>; Comment ***@***.***>
Asunto: Re: [LuimarcoCarrascalDiaz/Lab2SummerSchoolAI] Lab 2 (Issue #1)


Good afternoon Luimarco, I see you have not updated the code, I think it has been enough time, I will grade whatever is uploaded at the end of today.

Regards,
Juan Rodriguez

**Comment by LuimarcoCarrascalDiaz** [comment]
teacher sebastian, so i have updated the exercicses, in the first point i adjusted the prompts according to the examples provided, and in the second point i have completed the information extraction which at least terminates the process.

 Luimarco
________________________________
De: sebastianrodriguez1115 ***@***.***>
Enviado: martes, 23 de julio de 2024 3:51 p. m.
Para: LuimarcoCarrascalDiaz/Lab2SummerSchoolAI ***@***.***>
Cc: Luimarco Daniel Santiago Carrascal Diaz ***@***.***>; Comment ***@***.***>
Asunto: Re: [LuimarcoCarrascalDiaz/Lab2SummerSchoolAI] Lab 2 (Issue #1)


Good afternoon Luimarco, I see you have not updated the code, I think it has been enough time, I will grade whatever is uploaded at the end of today.

Regards,
Juan Rodriguez

**Comment by LuimarcoCarrascalDiaz** [comment]
Teacher, I have finally set the project correctly, and the point 2 of the lab is now fully working, in the point 1 I just changed the prompts to be more coherent with the examples provided by you

Luimarco
________________________________
De: sebastianrodriguez1115 ***@***.***>
Enviado: martes, 23 de julio de 2024 3:51 p. m.
Para: LuimarcoCarrascalDiaz/Lab2SummerSchoolAI ***@***.***>
Cc: Luimarco Daniel Santiago Carrascal Diaz ***@***.***>; Comment ***@***.***>
Asunto: Re: [LuimarcoCarrascalDiaz/Lab2SummerSchoolAI] Lab 2 (Issue #1)


Good afternoon Luimarco, I see you have not updated the code, I think it has been enough time, I will grade whatever is uploaded at the end of today.

Regards,
Juan Rodriguez

**Comment by sebastianrodriguez1115** [comment]
Perfect I'll grade it now, thanks!
